### ISSUE TITLE
acf-random-string-field-v4.php missing

### ISSUE THREAD

**Issue by strarsis** [lukechapman/acf-random-string-field#1]
When trying to enable this plugin, `acf-random-string-field-v4.php` cannot be found.

**Comment by lukechapman** [comment]
I've updated this now. Not currently supporting ACF4 so have removed the code looking to include the ACF4 version.

**Comment by strarsis** [comment]
@lukechapman: Are there any plans for near future for implementing v4 support?

**Comment by lukechapman** [comment]
@strarsis It shouldn't be too hard, I'll take a look at it
