### ISSUE TITLE
Can you explain how this field gets it randomized characters?

### ISSUE THREAD

**Issue by samjco** [lukechapman/acf-random-string-field#2]
Are they unique and Not duplicable?
Is it or can it be built off of the date, time, hours, min function?
Can they be formatted?

**Comment by Patabugen** [comment]
Hey @samjco 

I'm not the authour of this plugin (it's worth noting it's not been updated in 3 years though) and havent' actually used it - but came across your question and looked up the answer in the code:

https://github.com/lukechapman/acf-random-string-field/blob/master/js/input.js#L19

The string seems to be generated in JavaScript using the Math.random() function to pick a random letter each time.

It doesn't try to be always unique (like a date-based GUID does) but if you keep the string long you're very likely to not run into problems.

It doesn't have any filters or hooks to let you change the formatting - but you might be able to un-hook the existing Click event and add your own (copying and modifying the code to suit your needs).

**Comment by Patabugen** [comment]
In case it turns out to be important. there is a random string generated in PHP which doesn't appear to ever get used:

https://github.com/lukechapman/acf-random-string-field/blob/master/acf-random-string-field-v5.php#L46

**Comment by lukechapman** [comment]
@samjco Oh mate this is so out of date! I'm going to spend some time to re-write this and introduce all of the functionality you listed.

@Patabugen has answered your questions succinctly.
